version: '3.8'

services:
  web:
    build: .
    container_name: project4site-web
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY:-PLACEHOLDER_API_KEY}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-http://localhost:5433}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-test-key-for-local-validation}
    stdin_open: true
    tty: true
    restart: unless-stopped